apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: deleteme
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deleteme
    app.kubernetes.io/part-of: deleteme
  name: deleteme
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: deleteme
status:
  loadBalancer: {}
